modLoader = "javafml"
loaderVersion = "[38,40)"
issueTrackerURL = "https://github.com/TexTrueStudio/CrossPlatformCore/issues"
license = "MIT"

[[mods]]
modId = "crossplatformcore"
version = "${version}"
displayName = "CrossPlatformCore"
displayURL= "https://github.com/TexTrueStudio/CrossPlatformCore"
authors = "TexTrue, TexTrueStudio"
description = '''
A Cross ModLoader Lib
'''
logoFile = "icon.png"

[[dependencies.crossplatformcore]]
modId = "forge"
mandatory = true
versionRange = "[38,40)"
ordering = "NONE"
side = "BOTH"

[[dependencies.crossplatformcore]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.crossplatformcore]]
modId = "architectury"
mandatory = true
versionRange = "[3,4)"
ordering = "AFTER"
side = "BOTH"